"""Tests for the V1.5 distributed-tracing middleware (F-3, tasks VT1-VT2).

The tracing middleware is strictly additive and best-effort: it only adds an
``X-Trace-Id`` response header and binds ``trace_id`` into the logging context.
These tests exercise it over HTTP with ``fastapi.testclient``.

The header echo/generation tests use the trivial ``/`` route (a redirect with
no side effects). The log-context test drives ``/health`` with the same mocks
used by ``tests/test_api_query.py`` so no Ollama / Chroma / network is needed
and a deterministic ``api.main`` warning is emitted while the trace is bound.
"""

import logging
import uuid
from unittest.mock import MagicMock, patch

from fastapi.testclient import TestClient

from api.main import app
from api.tracing import TRACE_HEADER


class TestTraceIdHeader:
    def test_provided_trace_id_is_echoed(self):
        """A request carrying X-Trace-Id gets the SAME id echoed back."""
        client = TestClient(app)
        response = client.get(
            "/", headers={TRACE_HEADER: "test-trace-123"}, follow_redirects=False
        )
        assert response.headers.get(TRACE_HEADER) == "test-trace-123"

    def test_trace_id_generated_when_absent(self):
        """A request without X-Trace-Id gets a generated UUID4 in the header."""
        client = TestClient(app)
        response = client.get("/", follow_redirects=False)
        trace_id = response.headers.get(TRACE_HEADER)
        assert trace_id, "expected a generated X-Trace-Id response header"
        # Must be a valid UUID (UUID4 generated by the middleware).
        parsed = uuid.UUID(trace_id)
        assert parsed.version == 4

    def test_generated_ids_are_unique_per_request(self):
        """Each traceless request gets its own id (context is reset per request)."""
        client = TestClient(app)
        first = client.get("/", follow_redirects=False).headers.get(TRACE_HEADER)
        second = client.get("/", follow_redirects=False).headers.get(TRACE_HEADER)
        assert first and second
        assert first != second


class TestTraceIdLogContext:
    @patch("api.main.chromadb.PersistentClient")
    @patch("api.main.ollama.Client")
    @patch("api.main._get_db")
    @patch("api.main._load_config")
    def test_log_context_carries_trace_id(
        self, mock_load_cfg, mock_get_db, mock_ollama, mock_chroma, caplog
    ):
        """An api.main log record emitted during the request carries trace_id."""
        cfg = MagicMock()
        cfg.ollama.host = "http://localhost:11434"
        cfg.chroma_root_path = "/tmp/vault-tracing-test-chroma"
        cfg.models.embedding.collection_suffix = "test"
        cfg.models.language_id.model_path = "/tmp/vault-tracing-no-model.bin"
        mock_load_cfg.return_value = cfg
        mock_get_db.return_value = MagicMock()
        # Force the deterministic "Ollama not reachable" warning in /health.
        mock_ollama.side_effect = Exception("ollama unreachable")
        mock_chroma.return_value.get_collection.side_effect = Exception("no chroma")

        client = TestClient(app)
        with caplog.at_level(logging.WARNING, logger="api.main"):
            response = client.get("/health", headers={TRACE_HEADER: "trace-log-abc"})

        # Header still echoed (business response unchanged: /health returns 200).
        assert response.status_code == 200
        assert response.headers.get(TRACE_HEADER) == "trace-log-abc"

        # At least one api.main record carries the bound trace_id.
        traced = [
            record
            for record in caplog.records
            if getattr(record, "trace_id", None) == "trace-log-abc"
        ]
        assert traced, "expected an api.main log record carrying the bound trace_id"

    @patch("api.main.chromadb.PersistentClient")
    @patch("api.main.ollama.Client")
    @patch("api.main._get_db")
    @patch("api.main._load_config")
    def test_generated_trace_id_reaches_log_context(
        self, mock_load_cfg, mock_get_db, mock_ollama, mock_chroma, caplog
    ):
        """When no header is sent, the generated id is the one bound into logs."""
        cfg = MagicMock()
        cfg.ollama.host = "http://localhost:11434"
        cfg.chroma_root_path = "/tmp/vault-tracing-test-chroma"
        cfg.models.embedding.collection_suffix = "test"
        cfg.models.language_id.model_path = "/tmp/vault-tracing-no-model.bin"
        mock_load_cfg.return_value = cfg
        mock_get_db.return_value = MagicMock()
        mock_ollama.side_effect = Exception("ollama unreachable")
        mock_chroma.return_value.get_collection.side_effect = Exception("no chroma")

        client = TestClient(app)
        with caplog.at_level(logging.WARNING, logger="api.main"):
            response = client.get("/health")

        generated = response.headers.get(TRACE_HEADER)
        assert generated
        traced = [
            record
            for record in caplog.records
            if getattr(record, "trace_id", None) == generated
        ]
        assert traced, "expected the generated trace_id to be bound into the log context"
